/**
 * SSG Build Script for TABLES CMS
 * Generates static HTML files from CMS data for Vercel deployment
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const staticDir = join(rootDir, 'static');
const distDir = join(rootDir, 'dist');
const srcDir = join(rootDir, 'src');

// Ensure dist directory exists
if (!existsSync(distDir)) {
  mkdirSync(distDir, { recursive: true });
}

// Copy assets
const assetsDir = join(staticDir, 'assets');
if (existsSync(assetsDir)) {
  const distAssetsDir = join(distDir, 'assets');
  if (!existsSync(distAssetsDir)) {
    mkdirSync(distAssetsDir, { recursive: true });
  }
  copyDirectory(assetsDir, distAssetsDir);
}

// Copy CMS data
const cmsDir = join(staticDir, 'cms');
if (existsSync(cmsDir)) {
  const distCmsDir = join(distDir, 'cms');
  if (!existsSync(distCmsDir)) {
    mkdirSync(distCmsDir, { recursive: true });
  }
  copyDirectory(cmsDir, distCmsDir);
}

// Read CMS data
function loadCMSData() {
  const data = {
    pages: [],
    pageGroups: [],
    blogArticles: [],
    settings: {},
    extensions: {}
  };

  const files = {
    pages: 'pages.json',
    pageGroups: 'pageGroups.json',
    blogArticles: 'blogArticles.json',
    settings: 'settings.json',
    extensions: 'extensions.json'
  };

  for (const [key, file] of Object.entries(files)) {
    const filePath = join(cmsDir, file);
    if (existsSync(filePath)) {
      try {
        const content = readFileSync(filePath, 'utf-8');
        data[key] = JSON.parse(content);
      } catch (e) {
        console.warn(`Failed to load ${file}:`, e.message);
      }
    }
  }

  return data;
}

// Generate HTML template
function generateHTMLTemplate(title, content, cmsData = null) {
  const cmsDataScript = cmsData ? `<script>window.__CMS_DATA__ = ${JSON.stringify(cmsData)}</script>` : '';
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <meta name="description" content="Generated by TABLES CMS">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/main.css">
  ${cmsDataScript}
</head>
<body class="theme-default">
  <div id="app">${content}</div>
  <script type="module" src="/assets/js/main.js"></script>
</body>
</html>`;
}

// Generate page HTML from components
function generatePageHTML(page, cmsData) {
  const { name, components = [] } = page;
  
  let html = `<article class="page-content">`;
  
  if (components.length > 0) {
    for (const component of components) {
      html += renderComponent(component, cmsData);
    }
  } else {
    html += `<div class="page-body"><h1>${name}</h1></div>`;
  }
  
  html += `</article>`;
  return html;
}

// Render component based on type
function renderComponent(component, cmsData) {
  const { type, props = {} } = component;
  
  switch (type) {
    case 'hero':
      return `
        <section class="component-hero">
          ${props.image ? `<img src="${props.image}" alt="${props.title || ''}" class="hero-image">` : ''}
          <div class="hero-content">
            <h1 class="hero-title">${props.title || ''}</h1>
            ${props.subtitle ? `<p class="hero-subtitle">${props.subtitle}</p>` : ''}
            ${props.ctaText ? `<a href="${props.ctaLink || '#'}" class="btn btn-primary">${props.ctaText}</a>` : ''}
          </div>
        </section>
      `;
    
    case 'text':
      return `
        <section class="component-text">
          <div class="text-content">${props.content || ''}</div>
        </section>
      `;
    
    case 'image':
      return `
        <section class="component-image">
          <img src="${props.src || ''}" alt="${props.alt || ''}" ${props.caption ? `<figcaption>${props.caption}</figcaption>` : ''}>
        </section>
      `;
    
    case 'video':
      return `
        <section class="component-video">
          <div class="video-wrapper">
            <iframe src="${props.url || ''}" frameborder="0" allowfullscreen></iframe>
          </div>
        </section>
      `;
    
    case 'features':
      return `
        <section class="component-features">
          <h2>${props.title || 'Features'}</h2>
          <div class="features-grid">
            ${(props.items || []).map(item => `
              <div class="feature-card">
                ${item.icon ? `<i class="${item.icon}"></i>` : ''}
                <h3>${item.title || ''}</h3>
                <p>${item.description || ''}</p>
              </div>
            `).join('')}
          </div>
        </section>
      `;
    
    case 'cta':
      return `
        <section class="component-cta">
          <h2>${props.title || ''}</h2>
          <p>${props.description || ''}</p>
          <a href="${props.link || '#'}" class="btn btn-primary">${props.buttonText || 'Get Started'}</a>
        </section>
      `;
    
    case 'blog-list':
      const articles = cmsData?.blogArticles || [];
      return `
        <section class="component-blog-list">
          <h2>${props.title || 'Latest Articles'}</h2>
          <div class="blog-grid">
            ${articles.slice(0, props.limit || 6).map(article => `
              <article class="blog-card">
                <a href="/blog/${article.slug || article.id}">
                  ${article.image ? `<img src="${article.image}" alt="${article.title || ''}">` : ''}
                  <h3>${article.title || 'Untitled'}</h3>
                  <p class="blog-excerpt">${article.excerpt || ''}</p>
                  <span class="blog-date">${new Date(article.createdAt || Date.now()).toLocaleDateString()}</span>
                </a>
              </article>
            `).join('')}
          </div>
        </section>
      `;
    
    default:
      return '';
  }
}

// Generate blog article HTML
function generateBlogArticleHTML(article, cmsData) {
  return `
    <article class="blog-article">
      <header class="article-header">
        ${article.image ? `<img src="${article.image}" alt="${article.title || ''}" class="article-image">` : ''}
        <h1>${article.title || 'Untitled'}</h1>
        <div class="article-meta">
          ${article.author ? `<span class="author"><i class="fas fa-user"></i> ${article.author}</span>` : ''}
          <span class="date"><i class="fas fa-calendar"></i> ${new Date(article.createdAt || Date.now()).toLocaleDateString()}</span>
        </div>
        ${article.excerpt ? `<p class="article-excerpt">${article.excerpt}</p>` : ''}
      </header>
      <div class="article-content">
        ${article.content || ''}
      </div>
    </article>
  `;
}

// Generate main CSS
function generateMainCSS() {
  return `
/* TABLES CMS - Generated Styles */
:root {
  --primary: #2563eb;
  --primary-dark: #1d4ed8;
  --secondary: #10b981;
  --text: #0f172a;
  --text-light: #64748b;
  --bg: #ffffff;
  --bg-alt: #f8fafc;
  --border: #e2e8f0;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  color: var(--text);
  background: var(--bg);
  line-height: 1.6;
}

.theme-default { --bg: #ffffff; --text: #0f172a; }
.theme-synthwave { --bg: #2b213a; --text: #f5f5f5; --primary: #ff6b9d; }
.theme-matrix { --bg: #0d0208; --text: #00ff41; --primary: #008f11; }
.theme-monokai { --bg: #272822; --text: #f8f8f2; --primary: #a6e22e; }
.theme-github { --bg: #ffffff; --text: #24292e; --primary: #0366d6; }
.theme-vscode { --bg: #1e1e1e; --text: #d4d4d4; --primary: #007acc; }
.theme-anime { --bg: #ffeff5; --text: #ff6b9d; --primary: #ff1493; }
.theme-historic { --bg: #f4ecd8; --text: #5c4b37; --primary: #8b4513; }

.container { max-width: 1200px; margin: 0 auto; padding: 0 20px; }

.btn {
  display: inline-block;
  padding: 12px 24px;
  border-radius: 6px;
  font-weight: 600;
  text-decoration: none;
  transition: all 0.2s;
  cursor: pointer;
  border: none;
}

.btn-primary {
  background: var(--primary);
  color: white;
}

.btn-primary:hover { background: var(--primary-dark); }

/* Component Styles */
.component-hero {
  position: relative;
  min-height: 60vh;
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 80px 20px;
  background: linear-gradient(135deg, var(--primary), var(--primary-dark));
  color: white;
}

.hero-title { font-size: 3rem; margin-bottom: 16px; }
.hero-subtitle { font-size: 1.25rem; opacity: 0.9; margin-bottom: 32px; }

.component-text { padding: 60px 20px; max-width: 800px; margin: 0 auto; }
.component-text .text-content { font-size: 1.1rem; line-height: 1.8; }

.component-image { padding: 40px 20px; text-align: center; }
.component-image img { max-width: 100%; border-radius: 8px; }

.component-video { padding: 40px 20px; }
.video-wrapper { position: relative; padding-bottom: 56.25%; height: 0; }
.video-wrapper iframe { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }

.component-features { padding: 80px 20px; background: var(--bg-alt); }
.component-features h2 { text-align: center; margin-bottom: 40px; font-size: 2rem; }
.features-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 32px; max-width: 1200px; margin: 0 auto; }
.feature-card { background: var(--bg); padding: 32px; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); text-align: center; }
.feature-card i { font-size: 2.5rem; color: var(--primary); margin-bottom: 16px; }
.feature-card h3 { margin-bottom: 12px; }

.component-cta { padding: 80px 20px; text-align: center; background: linear-gradient(135deg, var(--primary), var(--secondary)); color: white; }
.component-cta h2 { font-size: 2rem; margin-bottom: 16px; }
.component-cta p { font-size: 1.1rem; margin-bottom: 32px; opacity: 0.9; }
.component-cta .btn { background: white; color: var(--primary); }

.component-blog-list { padding: 80px 20px; }
.component-blog-list h2 { text-align: center; margin-bottom: 40px; font-size: 2rem; }
.blog-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 32px; max-width: 1200px; margin: 0 auto; }
.blog-card { background: var(--bg); border-radius: 12px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.1); transition: transform 0.2s; }
.blog-card:hover { transform: translateY(-4px); }
.blog-card img { width: 100%; height: 200px; object-fit: cover; }
.blog-card h3 { padding: 16px 16px 8px; }
.blog-card .blog-excerpt { padding: 0 16px 16px; color: var(--text-light); }
.blog-card .blog-date { display: block; padding: 0 16px 16px; font-size: 0.875rem; color: var(--text-light); }
.blog-card a { text-decoration: none; color: inherit; }

.blog-article { max-width: 800px; margin: 0 auto; padding: 60px 20px; }
.article-header { margin-bottom: 40px; }
.article-image { width: 100%; border-radius: 12px; margin-bottom: 24px; }
.article-header h1 { font-size: 2.5rem; margin-bottom: 16px; }
.article-meta { display: flex; gap: 24px; color: var(--text-light); margin-bottom: 16px; }
.article-excerpt { font-size: 1.25rem; color: var(--text-light); }
.article-content { font-size: 1.1rem; line-height: 1.8; }

/* Responsive */
@media (max-width: 768px) {
  .hero-title { font-size: 2rem; }
  .features-grid { grid-template-columns: 1fr; }
}
`;
}

// Generate main JS
function generateMainJS() {
  return `
// TABLES CMS - Runtime JS
(function() {
  'use strict';
  
  // Load CMS data if available
  const cmsData = window.__CMS_DATA__ || null;
  
  // Theme switching
  function setTheme(themeName) {
    document.body.className = 'theme-' + themeName;
    localStorage.setItem('tables-theme', themeName);
  }
  
  // Load saved theme
  const savedTheme = localStorage.getItem('tables-theme') || 'default';
  setTheme(savedTheme);
  
  // Expose CMS data globally for components
  window.TABLES = { cmsData, setTheme };
  
  console.log('TABLES CMS loaded');
})();
`;
}

// Copy directory recursively
function copyDirectory(src, dest) {
  const entries = readdirSync(src, { withFileTypes: true });
  
  for (const entry of entries) {
    const srcPath = join(src, entry.name);
    const destPath = join(dest, entry.name);
    
    if (entry.isDirectory()) {
      if (!existsSync(destPath)) {
        mkdirSync(destPath, { recursive: true });
      }
      copyDirectory(srcPath, destPath);
    } else {
      copyFileSync(srcPath, destPath);
    }
  }
}

// Main build function
function build() {
  console.log('🔨 Starting SSG build...');
  
  const cmsData = loadCMSData();
  console.log('📄 Loaded CMS data:', {
    pages: cmsData.pages.length,
    pageGroups: cmsData.pageGroups.length,
    blogArticles: cmsData.blogArticles.length
  });
  
  // Generate assets
  const assetsDir = join(distDir, 'assets');
  const cssDir = join(assetsDir, 'css');
  const jsDir = join(assetsDir, 'js');
  
  if (!existsSync(cssDir)) mkdirSync(cssDir, { recursive: true });
  if (!existsSync(jsDir)) mkdirSync(jsDir, { recursive: true });
  
  writeFileSync(join(cssDir, 'main.css'), generateMainCSS());
  writeFileSync(join(jsDir, 'main.js'), generateMainJS());
  
  // Generate pages
  const pagesDir = join(distDir, 'pages');
  if (!existsSync(pagesDir)) mkdirSync(pagesDir, { recursive: true });
  
  let pagesGenerated = 0;
  for (const page of cmsData.pages || []) {
    const slug = page.slug || page.id || 'index';
    const html = generatePageHTML(page, cmsData);
    const content = generateHTMLTemplate(page.name || 'Page', html, cmsData);
    
    const filePath = join(distDir, `${slug === 'index' ? 'index' : slug}.html`);
    writeFileSync(filePath, content);
    pagesGenerated++;
  }
  
  // Generate blog articles
  const blogDir = join(distDir, 'blog');
  if (!existsSync(blogDir)) mkdirSync(blogDir, { recursive: true });
  
  let articlesGenerated = 0;
  for (const article of cmsData.blogArticles || []) {
    const slug = article.slug || article.id;
    const html = generateBlogArticleHTML(article, cmsData);
    const content = generateHTMLTemplate(article.title || 'Article', html, cmsData);
    
    const filePath = join(blogDir, `${slug}.html`);
    writeFileSync(filePath, content);
    articlesGenerated++;
  }
  
  // Generate index page if no pages exist
  if (pagesGenerated === 0) {
    const html = `
      <div class="container" style="padding: 80px 20px; text-align: center;">
        <h1 style="font-size: 2.5rem; margin-bottom: 20px;">Welcome to TABLES CMS</h1>
        <p style="font-size: 1.25rem; color: var(--text-light);">
          Start creating pages in the CMS to see them here.
        </p>
      </div>
    `;
    const content = generateHTMLTemplate('Home', html, cmsData);
    writeFileSync(join(distDir, 'index.html'), content);
  }
  
  // Generate blog index
  const blogIndexHtml = `
    <div class="container" style="padding: 80px 20px;">
      <h1 style="font-size: 2.5rem; margin-bottom: 40px; text-align: center;">Blog</h1>
      <div class="blog-grid">
        ${(cmsData.blogArticles || []).map(article => `
          <article class="blog-card">
            <a href="/blog/${article.slug || article.id}">
              ${article.image ? `<img src="${article.image}" alt="${article.title || ''}">` : ''}
              <h3>${article.title || 'Untitled'}</h3>
              <p class="blog-excerpt">${article.excerpt || ''}</p>
              <span class="blog-date">${new Date(article.createdAt || Date.now()).toLocaleDateString()}</span>
            </a>
          </article>
        `).join('')}
      </div>
      ${(cmsData.blogArticles || []).length === 0 ? '<p style="text-align: center; color: var(--text-light);">No articles yet.</p>' : ''}
    </div>
  `;
  writeFileSync(join(blogDir, 'index.html'), generateHTMLTemplate('Blog', blogIndexHtml, cmsData));
  
  console.log('✅ SSG build complete!');
  console.log(`   📄 Pages generated: ${pagesGenerated}`);
  console.log(`   📝 Blog articles: ${articlesGenerated}`);
  console.log(`   📁 Output directory: ${distDir}`);
}

// Run build
build();
